### ISSUE TITLE
Test Net Requirements

### ISSUE THREAD

**Issue by mvandeberg** [steemit/tinman#14]
Below are the main features of the test net. Other issues should be derived as a requirement from one of these.

- [ ] Snapshot Tool: Queries the main net for account and witness to export to the test net. (#16)

- [x] Genesis Conversion Tool: The conversion tool will take the output from the snapshot tool and create accounts on the test net that match the snapshot. (#17)

- [x] Tx Oracle Tool: The oracle will monitor the main net and convert certain main net transactions to the test net to simulate traffic on the test net. (#18)

- [ ] Kill Switch: The test net should automatically die after a certain block height. (steemit/steem#1732)

- [ ] Master/Slave Nodes: The testnet should be launched as either a master or a slave. The master runs the genesis tools and the Tx Oracle. Slaves connect to a seed node like a node normally would on the main net. Both configurations needs to be deployable and automated through Docker. (#19)(#20)

- [ ] Test Net Triggered Hardfork: When testing a new hardfork, the test net should launch on the previous hardfork and trigger the hardfork while the test net is running so that we can test the moment of the fork. (#21)
